### DO NOT EDIT BY HAND! this package was auto generated by pypi2nix ####
### For more info go to: https://www.github.com/offlinehacker/pypi2nix

{ pkgs, python, buildPythonPackage, self, overrides }:
  with pkgs.lib;
let
  isPy26 = python.majorVersion == "2.6";
  isPy27 = python.majorVersion == "2.7";
  isPy33 = python.majorVersion == "3.3";
  isPy34 = python.majorVersion == "3.4";
  isPyPy = python.executable == "pypy";

  # Unique python version identifier
  pythonName =
    if isPy26 then "python26" else
    if isPy27 then "python27" else
    if isPy33 then "python33" else
    if isPy34 then "python34" else
    if isPyPy then "pypy" else "";

  fetchurl = pkgs.fetchurl;

  callOverride = pkg: override:
    if (isFunction override) then (override pkg) else override;

  attrByPathAlternatives = alt: default: e:
    if alt==[] then default else
      attrByPath (head alt) (attrByPathAlternatives (drop 1 alt) default e) e;

  overridablePythonPackage = pkg: buildPythonPackage (
    pkg // (callOverride pkg (
      attrByPathAlternatives ([[pkg.basename] [pkg.name]]) {} overrides)
    )
  );

in {}
############### Aliases #####################################################

// (optionalAttrs (pythonName == "python27") {
  
  "graph-explorer" = self.by-version."graph-explorer-2.0.1";
  
  by-extra.default."graph-explorer" = self.by-version."graph-explorer-2.0.1";
  
  
  "sentry" = self.by-version."sentry-6.4.4";
  
  by-extra.postgres."sentry" = self.by-version."sentry-6.4.4";
  
  
  "graphite-api" = self.by-version."graphite-api-1.0.1";
  
  by-extra.default."graphite-api" = self.by-version."graphite-api-1.0.1";
  
  
})


############### Packages ####################################################
// {}

// (optionalAttrs (pythonName == "python27") {
  
  by-version."markupsafe-0.23" = overridablePythonPackage {
    name = "markupsafe-0.23";
    basename = "markupsafe";
    version = "0.23";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/M/MarkupSafe/MarkupSafe-0.23.tar.gz";
        md5 = "f5ab3deee4c37cd6a922fb81e730da6e";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."redis-2.8.0" = overridablePythonPackage {
    name = "redis-2.8.0";
    basename = "redis";
    version = "2.8.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/r/redis/redis-2.8.0.tar.gz";
        md5 = "3a5b1b96d70852a2581a0b28f6122902";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."graphite-influxdb-0.1.3" = overridablePythonPackage {
    name = "graphite-influxdb-0.1.3";
    basename = "graphite-influxdb";
    version = "0.1.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/g/graphite-influxdb/graphite-influxdb-0.1.3.tar.gz";
        md5 = "bab475798ba3b461eb8e7e2f82679353";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."influxdb-0.1.7" 
      
    ];
  };
  
  by-version."amqp-1.0.13" = overridablePythonPackage {
    name = "amqp-1.0.13";
    basename = "amqp";
    version = "1.0.13";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/a/amqp/amqp-1.0.13.tar.gz";
        md5 = "33e9e59f71a396f9cdd5d5d6a3d2e5d5";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."pysqlite-2.6.3" = overridablePythonPackage {
    name = "pysqlite-2.6.3";
    basename = "pysqlite";
    version = "2.6.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/pysqlite/pysqlite-2.6.3.tar.gz";
        md5 = "7ff1cedee74646b50117acff87aa1cfa";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."oauth2-1.5.211" = overridablePythonPackage {
    name = "oauth2-1.5.211";
    basename = "oauth2";
    version = "1.5.211";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/o/oauth2/oauth2-1.5.211.tar.gz";
        md5 = "987ad7365a70e2286bd1cebb344debbc";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."httplib2-0.9" 
      
    ];
  };
  
  by-version."eventlet-0.14.0" = overridablePythonPackage {
    name = "eventlet-0.14.0";
    basename = "eventlet";
    version = "0.14.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/e/eventlet/eventlet-0.14.0.tar.gz";
        md5 = "207119abce774018432225bd719403fb";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."greenlet-0.4.2" 
      
    ];
  };
  
  by-version."structlog-0.4.1" = overridablePythonPackage {
    name = "structlog-0.4.1";
    basename = "structlog";
    version = "0.4.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/s/structlog/structlog-0.4.1.tar.gz";
        md5 = "49441470a7eff0405c444c17daa1a9cb";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."pyyaml-3.11" = overridablePythonPackage {
    name = "pyyaml-3.11";
    basename = "pyyaml";
    version = "3.11";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.11.tar.gz";
        md5 = "f50e08ef0fe55178479d3a618efe21db";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."python-memcached-1.53" = overridablePythonPackage {
    name = "python-memcached-1.53";
    basename = "python-memcached";
    version = "1.53";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/python-memcached/python-memcached-1.53.tar.gz";
        md5 = "89570d26e7e7b15caa668a6b2678bd3c";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."django-paging-0.2.5" = overridablePythonPackage {
    name = "django-paging-0.2.5";
    basename = "django-paging";
    version = "0.2.5";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/d/django-paging/django-paging-0.2.5.tar.gz";
        md5 = "282ef984815f73ce43189d288b2bae2a";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."django-templatetag-sugar-0.1" 
      
    ];
  };
  
  by-version."simplejson-3.3.3" = overridablePythonPackage {
    name = "simplejson-3.3.3";
    basename = "simplejson";
    version = "3.3.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/s/simplejson/simplejson-3.3.3.tar.gz";
        md5 = "38ff12d163e5cc8c592d609820869817";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."py-1.4.20" = overridablePythonPackage {
    name = "py-1.4.20";
    basename = "py";
    version = "1.4.20";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/py/py-1.4.20.tar.gz";
        md5 = "5f1708be5482f3ff6711dfd6cafd45e0";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."futures-2.1.6" = overridablePythonPackage {
    name = "futures-2.1.6";
    basename = "futures";
    version = "2.1.6";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/f/futures/futures-2.1.6.tar.gz";
        md5 = "cfab9ac3cd55d6c7ddd0546a9f22f453";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."coverage-3.7.1" = overridablePythonPackage {
    name = "coverage-3.7.1";
    basename = "coverage";
    version = "3.7.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/coverage/coverage-3.7.1.tar.gz";
        md5 = "c47b36ceb17eaff3ecfab3bcd347d0df";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."pytz-2014.3" = overridablePythonPackage {
    name = "pytz-2014.3";
    basename = "pytz";
    version = "2014.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/pytz/pytz-2014.3.tar.bz2";
        md5 = "73ec19d78ae6a0e168c7ff781bde289d";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."elasticsearch-0.4.3" = overridablePythonPackage {
    name = "elasticsearch-0.4.3";
    basename = "elasticsearch";
    version = "0.4.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/e/elasticsearch/elasticsearch-0.4.3.tar.gz";
        md5 = "b6ec207c268e4d71374d7427065a623c";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."urllib3-1.7.1" 
      
    ];
  };
  
  by-version."cqlsh-4.1.1" = overridablePythonPackage {
    name = "cqlsh-4.1.1";
    basename = "cqlsh";
    version = "4.1.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/cqlsh/cqlsh-4.1.1.tar.gz";
        md5 = "2ee57265566304d9ef4ab1bb67dbaaf0";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."simplejson-3.3.3" self.by-version."unittest2-0.5.1" self.by-version."cql-1.4.0" 
      
    ];
  };
  
  by-version."pytest-django-2.6.2" = overridablePythonPackage {
    name = "pytest-django-2.6.2";
    basename = "pytest-django";
    version = "2.6.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/pytest-django/pytest-django-2.6.2.tar.gz";
        md5 = "3b3850a1f1f13826b3bcbd69f684edf9";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."pytest-2.5.2" 
      
    ];
  };
  
  by-version."mock-1.0.1" = overridablePythonPackage {
    name = "mock-1.0.1";
    basename = "mock";
    version = "1.0.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/m/mock/mock-1.0.1.tar.gz";
        md5 = "c3971991738caa55ec7c356bbc154ee2";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."django-crispy-forms-1.2.8" = overridablePythonPackage {
    name = "django-crispy-forms-1.2.8";
    basename = "django-crispy-forms";
    version = "1.2.8";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/d/django-crispy-forms/django-crispy-forms-1.2.8.tar.gz";
        md5 = "ed73111103ddaa39b6617a41eaee5c7e";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."kombu-2.5.16" = overridablePythonPackage {
    name = "kombu-2.5.16";
    basename = "kombu";
    version = "2.5.16";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/k/kombu/kombu-2.5.16.tar.gz";
        md5 = "e6a883288a962be7c64af5e1806a0f9e";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."anyjson-0.3.3" self.by-version."amqp-1.0.13" 
      
    ];
  };
  
  by-version."casscache-0.1.0" = overridablePythonPackage {
    name = "casscache-0.1.0";
    basename = "casscache";
    version = "0.1.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/casscache/casscache-0.1.0.tar.gz";
        md5 = "8b887eed2cd7efd3f9804476a6a2251b";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."cassandra-driver-1.1.2" 
      
    ];
  };
  
  by-version."paste-1.7.5.1" = overridablePythonPackage {
    name = "paste-1.7.5.1";
    basename = "paste";
    version = "1.7.5.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/P/Paste/Paste-1.7.5.1.tar.gz";
        md5 = "7ea5fabed7dca48eb46dc613c4b6c4ed";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."cassandra-driver-1.1.2" = overridablePythonPackage {
    name = "cassandra-driver-1.1.2";
    basename = "cassandra-driver";
    version = "1.1.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/cassandra-driver/cassandra-driver-1.1.2.tar.gz";
        md5 = "f1398e0de8d5ab599cc7a1c429d1c542";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."futures-2.1.6" 
      
    ];
  };
  
  by-version."httplib2-0.9" = overridablePythonPackage {
    name = "httplib2-0.9";
    basename = "httplib2";
    version = "0.9";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/h/httplib2/httplib2-0.9.tar.gz";
        md5 = "09d8e8016911fc40e2e4c58f1aa3ec24";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."exam-0.10.4" = overridablePythonPackage {
    name = "exam-0.10.4";
    basename = "exam";
    version = "0.10.4";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/e/exam/exam-0.10.4.tar.gz";
        md5 = "ed3c5d39dd725336236b9b857b4be971";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."mock-1.0.1" 
      
    ];
  };
  
  by-version."logan-0.5.10" = overridablePythonPackage {
    name = "logan-0.5.10";
    basename = "logan";
    version = "0.5.10";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/l/logan/logan-0.5.10.tar.gz";
        md5 = "ea9288dd1807f70e68c5404298147be6";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."itsdangerous-0.24" = overridablePythonPackage {
    name = "itsdangerous-0.24";
    basename = "itsdangerous";
    version = "0.24";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/i/itsdangerous/itsdangerous-0.24.tar.gz";
        md5 = "a3d55aa79369aef5345c036a8a26307f";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."httpretty-0.8.0" = overridablePythonPackage {
    name = "httpretty-0.8.0";
    basename = "httpretty";
    version = "0.8.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/h/httpretty/httpretty-0.8.0.tar.gz";
        md5 = "2d5ea5205c358fa489e6de6fc74c00fa";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."urllib3-1.7.1" 
      
    ];
  };
  
  by-version."pyparsing-2.0.2" = overridablePythonPackage {
    name = "pyparsing-2.0.2";
    basename = "pyparsing";
    version = "2.0.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/pyparsing/pyparsing-2.0.2.tar.gz";
        md5 = "b170c5d153d190df1a536988d88e95c1";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."python-coveralls-2.4.2" = overridablePythonPackage {
    name = "python-coveralls-2.4.2";
    basename = "python-coveralls";
    version = "2.4.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/python-coveralls/python-coveralls-2.4.2.tar.gz";
        md5 = "0f82aea84b365aae78de43e64ca6993d";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."six-1.6.1" self.by-version."sh-1.09" self.by-version."coverage-3.7.1" self.by-version."pyyaml-3.11" self.by-version."requests-2.3.0" 
      
    ];
  };
  
  by-version."cssutils-0.9.10" = overridablePythonPackage {
    name = "cssutils-0.9.10";
    basename = "cssutils";
    version = "0.9.10";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/cssutils/cssutils-0.9.10.zip";
        md5 = "81b5c0294c54479a54548769eaa236f8";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."pytest-timeout-0.3" = overridablePythonPackage {
    name = "pytest-timeout-0.3";
    basename = "pytest-timeout";
    version = "0.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/pytest-timeout/pytest-timeout-0.3.tar.gz";
        md5 = "46de81f106ab8a320c39a37d7d8f0429";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."pytest-2.5.2" 
      
    ];
  };
  
  by-version."six-1.6.1" = overridablePythonPackage {
    name = "six-1.6.1";
    basename = "six";
    version = "1.6.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/s/six/six-1.6.1.tar.gz";
        md5 = "07d606ac08595d795bf926cc9985674f";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."python-dateutil-1.5" = overridablePythonPackage {
    name = "python-dateutil-1.5";
    basename = "python-dateutil";
    version = "1.5";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/python-dateutil/python-dateutil-1.5.tar.gz";
        md5 = "0dcb1de5e5cad69490a3b6ab63f0cfa5";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."sentry-6.4.4" = overridablePythonPackage {
    name = "sentry-6.4.4";
    basename = "sentry";
    version = "6.4.4";

    src = fetchurl {
        url = "https://github.com/getsentry/sentry/archive/6.4.4.tar.gz";
        md5 = "da2118176fed1a28014d848c190376b8";
    };

    doCheck = true;

    buildInputs = [ self.by-version."pytest-2.5.2" self.by-version."pytest-django-2.6.2" self.by-version."nydus-0.10.7" self.by-version."redis-2.8.0" self.by-version."cqlsh-4.1.1" self.by-version."pytest-cov-1.6" self.by-version."exam-0.10.4" self.by-version."eventlet-0.14.0" self.by-version."httpretty-0.8.0" self.by-version."casscache-0.1.0" self.by-version."mock-1.0.1" self.by-version."unittest2-0.5.1" self.by-version."python-coveralls-2.4.2" self.by-version."pytest-timeout-0.3" self.by-version."riak-2.0.3" ];
    propagatedBuildInputs = [
      self.by-version."redis-2.8.0" self.by-version."south-0.8.2" self.by-version."pysqlite-2.6.3" self.by-version."python-memcached-1.53" self.by-version."django-paging-0.2.5" self.by-version."simplejson-3.3.3" self.by-version."django-picklefield-0.3.1" self.by-version."logan-0.5.10" self.by-version."cssutils-0.9.10" self.by-version."raven-4.2.3" self.by-version."python-dateutil-1.5" self.by-version."beautifulsoup-3.2.1" self.by-version."django-static-compiler-0.3.3" self.by-version."httpagentparser-1.2.2" self.by-version."setproctitle-1.1.8" self.by-version."django-celery-3.0.23" self.by-version."django-templatetag-sugar-0.1" self.by-version."pygments-1.6" self.by-version."urllib3-1.7.1" self.by-version."celery-3.0.24" self.by-version."nydus-0.10.7" self.by-version."gunicorn-0.17.4" self.by-version."django-crispy-forms-1.2.8" self.by-version."django-social-auth-0.7.28" self.by-version."django-1.5.8" self.by-version."pynliner-0.5.1" self.by-version."email-reply-parser-0.2.0" 
      self.by-version."psycopg2-2.5.3" 
    ];
  };
  
  by-version."werkzeug-0.9.4" = overridablePythonPackage {
    name = "werkzeug-0.9.4";
    basename = "werkzeug";
    version = "0.9.4";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/W/Werkzeug/Werkzeug-0.9.4.tar.gz";
        md5 = "670fad41f57c13b71a6816765765a3dd";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."python-openid-2.2.5" = overridablePythonPackage {
    name = "python-openid-2.2.5";
    basename = "python-openid";
    version = "2.2.5";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/python-openid/python-openid-2.2.5.tar.gz";
        md5 = "393f48b162ec29c3de9e2973548ea50d";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."greenlet-0.4.2" = overridablePythonPackage {
    name = "greenlet-0.4.2";
    basename = "greenlet";
    version = "0.4.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/g/greenlet/greenlet-0.4.2.zip";
        md5 = "580a8a5e833351f7abdaedb1a877f7ac";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."beautifulsoup-3.2.1" = overridablePythonPackage {
    name = "beautifulsoup-3.2.1";
    basename = "beautifulsoup";
    version = "3.2.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/B/BeautifulSoup/BeautifulSoup-3.2.1.tar.gz";
        md5 = "44656527ef3ac9874ac4d1c9f35f70ee";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."django-static-compiler-0.3.3" = overridablePythonPackage {
    name = "django-static-compiler-0.3.3";
    basename = "django-static-compiler";
    version = "0.3.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/d/django-static-compiler/django-static-compiler-0.3.3.tar.gz";
        md5 = "019f9aa814fa96cbb298686ce6abdeab";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."django-1.5.8" 
      
    ];
  };
  
  by-version."pytest-cov-1.6" = overridablePythonPackage {
    name = "pytest-cov-1.6";
    basename = "pytest-cov";
    version = "1.6";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/pytest-cov/pytest-cov-1.6.tar.gz";
        md5 = "6da54d74bde9d200de45068ba2ea637a";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."cov-core-1.12" self.by-version."pytest-2.5.2" 
      
    ];
  };
  
  by-version."influxdb-0.1.7" = overridablePythonPackage {
    name = "influxdb-0.1.7";
    basename = "influxdb";
    version = "0.1.7";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/i/influxdb/influxdb-0.1.7.tar.gz";
        md5 = "d89d3308259e51861c69079422f4d73c";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."requests-2.3.0" 
      
    ];
  };
  
  by-version."requests-2.3.0" = overridablePythonPackage {
    name = "requests-2.3.0";
    basename = "requests";
    version = "2.3.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/r/requests/requests-2.3.0.tar.gz";
        md5 = "7449ffdc8ec9ac37bbcd286003c80f00";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."raven-4.2.3" = overridablePythonPackage {
    name = "raven-4.2.3";
    basename = "raven";
    version = "4.2.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/r/raven/raven-4.2.3.tar.gz";
        md5 = "2f51799716c94dc6dfced585ba428a4d";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."flask-0.10.1" = overridablePythonPackage {
    name = "flask-0.10.1";
    basename = "flask";
    version = "0.10.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/F/Flask/Flask-0.10.1.tar.gz";
        md5 = "378670fe456957eb3c27ddaef60b2b24";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."werkzeug-0.9.4" self.by-version."itsdangerous-0.24" self.by-version."jinja2-2.7.2" 
      
    ];
  };
  
  by-version."riak-pb-1.4.4.0" = overridablePythonPackage {
    name = "riak-pb-1.4.4.0";
    basename = "riak-pb";
    version = "1.4.4.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/r/riak_pb/riak_pb-1.4.4.0.tar.gz";
        md5 = "17d053dea083fdbaed1caaebed3461bd";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."protobuf-2.4.1" 
      
    ];
  };
  
  by-version."wtforms-2.0" = overridablePythonPackage {
    name = "wtforms-2.0";
    basename = "wtforms";
    version = "2.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/W/WTForms/WTForms-2.0.zip";
        md5 = "e235f22bf5bbbca8dd1072c05fd18137";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."httpagentparser-1.2.2" = overridablePythonPackage {
    name = "httpagentparser-1.2.2";
    basename = "httpagentparser";
    version = "1.2.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/h/httpagentparser/httpagentparser-1.2.2.tar.gz";
        md5 = "5e2e43769bf81d959484576f8dabaae4";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."riak-2.0.3" = overridablePythonPackage {
    name = "riak-2.0.3";
    basename = "riak";
    version = "2.0.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/r/riak/riak-2.0.3.tar.gz";
        md5 = "876dea2b30ccdcc0cb285e329d0119ef";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."riak-pb-1.4.4.0" 
      
    ];
  };
  
  by-version."django-celery-3.0.23" = overridablePythonPackage {
    name = "django-celery-3.0.23";
    basename = "django-celery";
    version = "3.0.23";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/d/django-celery/django-celery-3.0.23.tar.gz";
        md5 = "76e72fa09319909da22adcf13a7e6af1";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."pytz-2014.3" self.by-version."celery-3.0.24" 
      
    ];
  };
  
  by-version."anyjson-0.3.3" = overridablePythonPackage {
    name = "anyjson-0.3.3";
    basename = "anyjson";
    version = "0.3.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/a/anyjson/anyjson-0.3.3.tar.gz";
        md5 = "2ea28d6ec311aeeebaf993cb3008b27c";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."protobuf-2.4.1" = overridablePythonPackage {
    name = "protobuf-2.4.1";
    basename = "protobuf";
    version = "2.4.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/protobuf/protobuf-2.4.1.tar.gz";
        md5 = "72f5141d20ab1bcae6b1e00acfb1068a";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."setuptools-3.6" 
      
    ];
  };
  
  by-version."graph-explorer-2.0.1" = overridablePythonPackage {
    name = "graph-explorer-2.0.1";
    basename = "graph-explorer";
    version = "2.0.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/g/graph-explorer/graph-explorer-2.0.1.tar.gz";
        md5 = "c268f4899179337857a6d0135aac2617";
    };

    doCheck = true;

    buildInputs = [ self.by-version."setuptools-git-1.0" self.by-version."pytest-2.5.2" ];
    propagatedBuildInputs = [
      self.by-version."paste-1.7.5.1" self.by-version."bottle-0.11.6" self.by-version."wtforms-2.0" self.by-version."argparse-1.2.1" self.by-version."urllib3-1.7.1" self.by-version."elasticsearch-0.4.3" 
      
    ];
  };
  
  by-version."django-templatetag-sugar-0.1" = overridablePythonPackage {
    name = "django-templatetag-sugar-0.1";
    basename = "django-templatetag-sugar";
    version = "0.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/d/django-templatetag-sugar/django-templatetag-sugar-0.1.tar.gz";
        md5 = "f5b8bf6e4cb82f8affa761574bf3dae4";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."cql-1.4.0" = overridablePythonPackage {
    name = "cql-1.4.0";
    basename = "cql";
    version = "1.4.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/cql/cql-1.4.0.tar.gz";
        md5 = "ee3f4c5178335cb65bbbd55bb808e1ae";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."thrift-0.9.1" 
      
    ];
  };
  
  by-version."cov-core-1.12" = overridablePythonPackage {
    name = "cov-core-1.12";
    basename = "cov-core";
    version = "1.12";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/cov-core/cov-core-1.12.tar.gz";
        md5 = "4982572cfb179bbc004cf3c334686561";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."coverage-3.7.1" 
      
    ];
  };
  
  by-version."setuptools-git-1.0" = overridablePythonPackage {
    name = "setuptools-git-1.0";
    basename = "setuptools-git";
    version = "1.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/s/setuptools-git/setuptools-git-1.0.tar.gz";
        md5 = "de63b541a10c2b83caa478c687458b16";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."urllib3-1.7.1" = overridablePythonPackage {
    name = "urllib3-1.7.1";
    basename = "urllib3";
    version = "1.7.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/u/urllib3/urllib3-1.7.1.tar.gz";
        md5 = "8b05bb2081379fe3c332542aa7c172f3";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."setproctitle-1.1.8" = overridablePythonPackage {
    name = "setproctitle-1.1.8";
    basename = "setproctitle";
    version = "1.1.8";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/s/setproctitle/setproctitle-1.1.8.tar.gz";
        md5 = "728f4c8c6031bbe56083a48594027edd";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."celery-3.0.24" = overridablePythonPackage {
    name = "celery-3.0.24";
    basename = "celery";
    version = "3.0.24";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/celery/celery-3.0.24.tar.gz";
        md5 = "e864856a849468f277031ac2c5fd65b6";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."billiard-2.7.3.34" self.by-version."python-dateutil-1.5" self.by-version."kombu-2.5.16" 
      
    ];
  };
  
  by-version."graphite-api-1.0.1" = overridablePythonPackage {
    name = "graphite-api-1.0.1";
    basename = "graphite-api";
    version = "1.0.1";

    src = fetchurl {
        url = "https://github.com/brutasse/graphite-api/archive/1.0.1.tar.gz";
        md5 = "e9993841f9d45c770e3b3f10daf6d175";
    };

    doCheck = true;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."pytz-2014.3" self.by-version."graphite-influxdb-0.1.3" self.by-version."structlog-0.4.1" self.by-version."flask-0.10.1" self.by-version."cairocffi-0.5.4" self.by-version."pyparsing-2.0.2" self.by-version."six-1.6.1" self.by-version."pyyaml-3.11" 
      
    ];
  };
  
  by-version."pytest-2.5.2" = overridablePythonPackage {
    name = "pytest-2.5.2";
    basename = "pytest";
    version = "2.5.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/pytest/pytest-2.5.2.tar.gz";
        md5 = "8ea3d1939e81514ccba9ba0e9566b5be";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."py-1.4.20" 
      
    ];
  };
  
  by-version."nydus-0.10.7" = overridablePythonPackage {
    name = "nydus-0.10.7";
    basename = "nydus";
    version = "0.10.7";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/n/nydus/nydus-0.10.7.tar.gz";
        md5 = "89ed21582f9cff79a8bca74854b05a64";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."jinja2-2.7.2" = overridablePythonPackage {
    name = "jinja2-2.7.2";
    basename = "jinja2";
    version = "2.7.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/J/Jinja2/Jinja2-2.7.2.tar.gz";
        md5 = "df1581455564e97010e38bc792012aa5";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."markupsafe-0.23" 
      
    ];
  };
  
  by-version."gunicorn-0.17.4" = overridablePythonPackage {
    name = "gunicorn-0.17.4";
    basename = "gunicorn";
    version = "0.17.4";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/g/gunicorn/gunicorn-0.17.4.tar.gz";
        md5 = "464c1d0ce93c62ce039dc9a9493d26e3";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."django-picklefield-0.3.1" = overridablePythonPackage {
    name = "django-picklefield-0.3.1";
    basename = "django-picklefield";
    version = "0.3.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/d/django-picklefield/django-picklefield-0.3.1.tar.gz";
        md5 = "69712c8744502f2bf179c7fbed0006ef";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."six-1.6.1" 
      
    ];
  };
  
  by-version."pygments-1.6" = overridablePythonPackage {
    name = "pygments-1.6";
    basename = "pygments";
    version = "1.6";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/P/Pygments/Pygments-1.6.tar.gz";
        md5 = "a18feedf6ffd0b0cc8c8b0fbdb2027b1";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."south-0.8.2" = overridablePythonPackage {
    name = "south-0.8.2";
    basename = "south";
    version = "0.8.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/S/South/South-0.8.2.tar.gz";
        md5 = "89e61dd2cddab43d4de73d82321c61e6";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."pycparser-2.10" = overridablePythonPackage {
    name = "pycparser-2.10";
    basename = "pycparser";
    version = "2.10";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/pycparser/pycparser-2.10.tar.gz";
        md5 = "d87aed98c8a9f386aa56d365fe4d515f";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."django-social-auth-0.7.28" = overridablePythonPackage {
    name = "django-social-auth-0.7.28";
    basename = "django-social-auth";
    version = "0.7.28";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/d/django-social-auth/django-social-auth-0.7.28.tar.gz";
        md5 = "50fb14cc829fc28d6021e711e206f228";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."oauth2-1.5.211" self.by-version."python-openid-2.2.5" self.by-version."django-1.5.8" 
      
    ];
  };
  
  by-version."django-1.5.8" = overridablePythonPackage {
    name = "django-1.5.8";
    basename = "django";
    version = "1.5.8";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/D/Django/Django-1.5.8.tar.gz";
        md5 = "675fc736e2c29090f005e217ccf90b5b";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."cffi-0.8.2" = overridablePythonPackage {
    name = "cffi-0.8.2";
    basename = "cffi";
    version = "0.8.2";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/cffi/cffi-0.8.2.tar.gz";
        md5 = "37fc88c62f40d04e8a18192433f951ec";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."pycparser-2.10" 
      
    ];
  };
  
  by-version."billiard-2.7.3.34" = overridablePythonPackage {
    name = "billiard-2.7.3.34";
    basename = "billiard";
    version = "2.7.3.34";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/b/billiard/billiard-2.7.3.34.tar.gz";
        md5 = "9ecf0a3dbbd023e1fe9830b40d397d70";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."cairocffi-0.5.4" = overridablePythonPackage {
    name = "cairocffi-0.5.4";
    basename = "cairocffi";
    version = "0.5.4";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/c/cairocffi/cairocffi-0.5.4.tar.gz";
        md5 = "e3fa4002583bfaa88b156e1af9c75bde";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."cffi-0.8.2" 
      
    ];
  };
  
  by-version."bottle-0.11.6" = overridablePythonPackage {
    name = "bottle-0.11.6";
    basename = "bottle";
    version = "0.11.6";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/b/bottle/bottle-0.11.6.tar.gz";
        md5 = "0bafdc4e13ea2b1a3bddf36b5af108c4";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."argparse-1.2.1" = overridablePythonPackage {
    name = "argparse-1.2.1";
    basename = "argparse";
    version = "1.2.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/a/argparse/argparse-1.2.1.tar.gz";
        md5 = "2fbef8cb61e506c706957ab6e135840c";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."pynliner-0.5.1" = overridablePythonPackage {
    name = "pynliner-0.5.1";
    basename = "pynliner";
    version = "0.5.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/pynliner/pynliner-0.5.1.tar.gz";
        md5 = "563bcfb5bd42f54b79c62cbf24972dfc";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      self.by-version."beautifulsoup-3.2.1" self.by-version."cssutils-0.9.10" 
      
    ];
  };
  
  by-version."sh-1.09" = overridablePythonPackage {
    name = "sh-1.09";
    basename = "sh";
    version = "1.09";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/s/sh/sh-1.09.tar.gz";
        md5 = "b68a2f91de880dce042d4f03ec9e0f47";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."email-reply-parser-0.2.0" = overridablePythonPackage {
    name = "email-reply-parser-0.2.0";
    basename = "email-reply-parser";
    version = "0.2.0";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/e/email_reply_parser/email_reply_parser-0.2.0.tar.gz";
        md5 = "6fb93cf85eca7916b6e8db6cb67a8f53";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."unittest2-0.5.1" = overridablePythonPackage {
    name = "unittest2-0.5.1";
    basename = "unittest2";
    version = "0.5.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/u/unittest2/unittest2-0.5.1.tar.gz";
        md5 = "a0af5cac92bbbfa0c3b0e99571390e0f";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."thrift-0.9.1" = overridablePythonPackage {
    name = "thrift-0.9.1";
    basename = "thrift";
    version = "0.9.1";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/t/thrift/thrift-0.9.1.tar.gz";
        md5 = "8989a8a96b0e3a3380cfb89c44e172a6";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."setuptools-3.6" = overridablePythonPackage {
    name = "setuptools-3.6";
    basename = "setuptools";
    version = "3.6";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/s/setuptools/setuptools-3.6.tar.gz";
        md5 = "8f3a1dcdc14313c8334eb6af4f66ea0a";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
  by-version."psycopg2-2.5.3" = overridablePythonPackage {
    name = "psycopg2-2.5.3";
    basename = "psycopg2";
    version = "2.5.3";

    src = fetchurl {
        url = "https://pypi.python.org/packages/source/p/psycopg2/psycopg2-2.5.3.tar.gz";
        md5 = "09dcec70f623a9ef774f1aef75690995";
    };

    doCheck = false;

    buildInputs = [ ];
    propagatedBuildInputs = [
      
      
    ];
  };
  
})
