[
  ./attributes.nix
  ./terminal.nix
  ./environments

  ./profiles/vim
  ./profiles/tmux
  ./profiles/st
  ./profiles/x11
  ./profiles/x11/themes/numix-solarized.nix
  ./profiles/docker.nix
  ./profiles/vbox.nix
  ./profiles/kubernetes.nix
  ./profiles/i3.nix
  ./profiles/wireshark.nix

  ./roles/base.nix
  ./roles/admin.nix
  ./roles/server.nix
  ./roles/headless.nix
  ./roles/work.nix
  ./roles/multimedia.nix
  ./roles/anonymous.nix
  ./roles/office.nix
  ./roles/dev
  ./roles/dev/node.nix
  ./roles/dev/android.nix
  ./roles/dev/ruby.nix
  ./roles/dev/nix.nix
  ./roles/dev/python.nix
  ./roles/dev/go.nix
  ./roles/desktop.nix
  ./roles/vm.nix
  ./roles/system.nix
  ./roles/pentest.nix
  ./roles/laptop.nix
]
