[
  ./attributes.nix

  ./profiles/terminal.nix
  ./profiles/vim
  ./profiles/tmux
  ./profiles/st
  ./profiles/xterm.nix
  ./profiles/x11
  ./profiles/x11/themes/numix-solarized.nix
  ./profiles/docker.nix
  ./profiles/vbox.nix
  ./profiles/kubernetes.nix
  ./profiles/i3.nix
  ./profiles/wireshark.nix
  ./profiles/libvirt.nix
  ./profiles/qemu.nix
  ./profiles/taskwarrior.nix
  ./profiles/xonsh.nix
  ./profiles/dunst.nix
  ./profiles/bluetooth.nix
  ./profiles/pulseaudio.nix
  ./profiles/udisks.nix
  ./profiles/networkmanager.nix
  ./profiles/yubikey.nix
  ./profiles/xsuspender.nix
  ./profiles/printingAndScanning.nix

  ./roles/base.nix
  ./roles/admin.nix
  ./roles/server.nix
  ./roles/headless.nix
  ./roles/work.nix
  ./roles/workstation.nix
  ./roles/multimedia.nix
  ./roles/anonymous.nix
  ./roles/dev
  ./roles/dev/node.nix
  ./roles/dev/android.nix
  ./roles/dev/ruby.nix
  ./roles/dev/nix.nix
  ./roles/dev/python.nix
  ./roles/dev/go.nix
  ./roles/dev/devops.nix
  ./roles/dev/elm.nix
  ./roles/desktop.nix
  ./roles/vm.nix
  ./roles/system.nix
  ./roles/pentest.nix
  ./roles/laptop.nix
]
