[
  ./base.nix
  ./passthru.nix
  ../attributes.nix

  ./profiles/audio.nix
  ./profiles/bluetooth.nix
  ./profiles/chromium.nix
  ./profiles/firefox
  ./profiles/dunst.nix
  ./profiles/gpg.nix
  ./profiles/i3.nix
  ./profiles/networking.nix
  ./profiles/redshift.nix
  ./profiles/terminal.nix
  ./profiles/tmux.nix
  ./profiles/udisks.nix
  ./profiles/vim.nix
  ./profiles/xsession.nix
  ./profiles/xsuspender.nix
  ./profiles/xterm.nix
  ./profiles/wireshark.nix
  ./profiles/yubikey.nix
  ./profiles/firejail.nix

  ./roles/work.nix
  ./roles/workstation.nix
  ./roles/multimedia.nix
  ./roles/pentest.nix
  ./roles/admin.nix
  ./roles/crypto.nix
  ./roles/forensics.nix
  ./roles/dev/default.nix
  ./roles/dev/android.nix
  ./roles/dev/devops.nix
  ./roles/dev/elm.nix
  ./roles/dev/go.nix
  ./roles/dev/nix.nix
  ./roles/dev/node.nix
  ./roles/dev/python.nix
  ./roles/dev/ruby.nix
  ./roles/dev/haskell.nix

  ./themes/numix-solarized.nix
]
