[
  ./home-manager.nix
  ./user-env.nix
  ./nixos-init.nix
  ./xephyr-session.nix
  ./user-env-xephyr.nix
  ./recovery.nix
  ./low-battery-check.nix
  ./share-wayland-socket.nix
  ./loginctl-linger.nix
]
